//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservice5
{
    using System;
    using System.Collections.Generic;
    
    public partial class iservice_timeline
    {
        public int iservice_timeline_id { get; set; }
        public int iservice_timeline_user_id { get; set; }
        public System.DateTime iservice_timeline_start_time { get; set; }
        public System.DateTime iservice_timeline_end_time { get; set; }
    
        public virtual iservice_users iservice_users { get; set; }
    }
}
