//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservice5
{
    using System;
    using System.Collections.Generic;
    
    public partial class iservice_orders_items
    {
        public int iservice_orders_items_id { get; set; }
        public int iservice_orders_items_orders_id { get; set; }
        public int iservice_orders_item_id { get; set; }
        public string iservice_orders_items_price_netto { get; set; }
        public string iservice_orders_items_price_brutto { get; set; }
    
        public virtual iservice_items iservice_items { get; set; }
        public virtual iservice_orders iservice_orders { get; set; }
    }
}
