//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservice5
{
    using System;
    using System.Collections.Generic;

    public class iservice_customers
    {
        public int iservice_customers_id { get; set; }
        public string iservice_customers_name { get; set; }
        public string iservice_customers_surname { get; set; }
        public string iservice_customers_patronymic { get; set; }
        public string iservice_customers_country { get; set; }
        public string iservice_customers_city { get; set; }
        public string iservice_customers_street { get; set; }
        public string iservice_customers_zipcode { get; set; }
        public string iservice_customers_telephone { get; set; }
        public string iservice_customers_telephone_home { get; set; }
        public string iservice_customers_date_of_birthday { get; set; }
        public string iservice_customers_email { get; set; }
        public string iservice_customers_date_of_creation { get; set; }
        public string iservice_customers_employee { get; set; }
        public string iservice_customers_company { get; set; }
       // public virtual ICollection<iservice_cars> iservice_cars { get; set; }

    }
}
