//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iservice5
{
    using System;
    using System.Collections.Generic;
    
    public partial class iservice_users
    {
     
    
        public int iservice_users_id { get; set; }
        public string iservice_users_name { get; set; }
        public string iservice_users_surname { get; set; }
        public string iservice_users_patronymic { get; set; }
        public string iservice_users_address { get; set; }
        public string iservice_users_telephone { get; set; }
        public string iservice_users_telephone_home { get; set; }
        public string iservice_users_date_of_birthday { get; set; }
        public string iservice_users_email { get; set; }
        public string iservice_users_access { get; set; }
        public string iservice_users_date_of_creation { get; set; }
        public string iservice_users_password { get; set; }

    }
}
